language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-google_play_services

before_install:
- echo 'Decrypt sign key'
- openssl aes-256-cbc -K $encrypted_55c0631e3f2b_key -iv $encrypted_55c0631e3f2b_iv -in signkey.pem.enc -out signkey.pem -d

install:
- echo 'Install dependences'

before_script:
- echo 'Retrieve the last build status'
- export BUILD_NUM=$((1000+$TRAVIS_BUILD_NUMBER))
- export BUILD_ARTIFACTS_FOLDER="build"
- export BUILD_ARTIFACTS_FILE=$BUILD_ARTIFACTS_FOLDER"/"$BUILD_NUM".txt"
- mkdir $BUILD_ARTIFACTS_FOLDER
- copy signkey.pem $BUILD_ARTIFACTS_FOLDER

script:
- echo 'Run the build script and test'
- "./Build.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $BUILD_NUM > $BUILD_ARTIFACTS_FILE"

deploy:
  provider: s3
  access_key_id:
    secure: FVuBo22eWSQ1aV6SujwB3GlH3uyUyyvtwaFT0oSbdsFyJCC57pNObFGJmNN0knhDK3wGgPNR2RaeWb5L7EWRh99j2tah1JaNZsWWacKBOyNVvo0n64ozZjjTT1yTXttZC6zOcPIWxrh8JJerT1Ov/j+pDH95lJxsZaHAY+Bg0UdGT7F7LxBkuStRVg8BPrqVvXpc6wJVKiY78CPwb9/CYAxW4Yh9P4o0Zc/6QQSV2WqCJJ5lKipdFnShC458HWiu8/QL4BowFcBGjfmdjAQXoWIwY0p7r96sBo42tuE9sxPW0vzijFJLM2G8HjEu0Y8Cl1oJjAA/SgP+AEAnWHPE3PJPPk86Yx0Z4UdqR1tM5G9r7XWfvlyjwRBsnTcH8UAekwxwKQHYtI81DWQDa7IcJ7KEnNZAHcr4ygSipRmSOz6uJ/avqYUZfXbipaIAUX39zSPYkcyyb1cpOmqkEm2quVD7KrN0t3sYCBHWuyVo29PhVy4ArpiUBOQNF2OrpOROsrt4eKZlx5SRGdoAawA4xQyKd9679zXvEtgLTlbQn0AdbKRYYUxZZ8eY2O1FcPARE1tBhxm2MoYHUd9ByUFVv+tSthIJWGjQ13vD6RN99t1gJ16aGiMobRvkAUCUaS61r4wDg7NJMeC4ynQqq+rkhGO1BDSgc6xhZbLTbrjmhZE=
  secret_access_key:
    secure: sI9djoHmmEY3NygmQ/JdXxvQjOGCGLSD178p6Jgs5Rom/ZfxFJHoWCelkdA5a2TI4/vX60DcwrHYa2gbkEpZE+WPq5kAjSnLVeIWmV2cWpXTItlJAp35cAOZxn3UVqBnKIxAse5HsN5mzkN76MrwoaxHKJaNLWzOrk5nPmR9f1ZamZvJXlyTaw1KPHyszFPJmguTZtFG9LtWjN8OwgtOgfNE7lketjDBc+xg1q2INGP9mbO/b96u22k4e0xrDpIXPJsi1HSAliies7AnAp1BASZVtk9c7geTdl7Sv21Ni9TJDzZBpxs549ZJBoefYWjR68HYtX/wq/EGpTD3Tg94Tp1ULbtzgnwNfsMOU/ISKVpxdIvfRqJt6isLfBY37FEaHhgqo5709KrhhPXga8BVj1jQ7PSBJ3FJ5356Tpu4otKTLOFMApVwEWFi7ouzTNdqS7nOK0zCpDtQtIRYTktafbTVCGFcJnGBR0Ie9fve57UiO/G/dfrTlklaO4WyryUwZ9rQKua0e440/QescM4lGDVJ1PxaUtM8h2MFYdPIfPFbWT82vLVsIfj9oQOb251FXgyOneqwm9qppRHIbCAOIw5dRSLgdEx4JuwLwL2uake52cjzfAiZMYy74hGmwSokhEmyB3eFfndKeKuhvfr27j4xPWz/w3WKloRyJEC9GMI=
  bucket: doctor-mobile-build-artifacts
  skip_cleanup: true
  region: us-west-1
  detect_encoding: true
  local-dir: "$BUILD_ARTIFACTS_FOLDER"
  upload-dir: "$BUILD_NUM"
  acl: private

notifications:
  email:
    recipients:
    - jonas_cheng@trend.com.tw
    on_success: always
    on_failure: always
