language: android
android:
# You can define the list of SDK components to be installed
  components:
    - build-tools-19.1.0
    - android-19
    - extra-google-google_play_services

# If your project is built with Ant or any other build tool that does not
# automatically handle dependences, you need to specify the exact command
# to run using install: key.
install:
  - echo 'Install dependences'

before_script:
# Retrieve the last build status
  - echo 'Retrieve the last build status'
  - export BUILD_NUM=1000
  - echo '$BUILD_NUM'
  - echo '$TRAVIS_BRANCH'
  - echo '$DEBIAN_FRONTEND'

script: 
# Run the build script and test
  - echo 'Run the build script and test

after_success:
# Update build status and upload artifacts
  - echo 'Update build status and upload artifacts'

notifications:
  email:
    recipients:
      - jonas_cheng@trend.com.tw
    on_success: always
    on_failure: always
