language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-google_play_services

install:
- echo 'Install dependences'

before_script:
- echo 'Retrieve the last build status'
- export BUILD_NUM=`expr 1000+$TRAVIS_BUILD_NUMBER`
- export BUILD_ARTIFACTS_FOLDER="build"
- export BUILD_ARTIFACTS_FILE=$BUILD_ARTIFACTS_FOLDER"/"$BUILD_NUM+".txt"
- mkdir $BUILD_ARTIFACTS_FOLDER

script:
- echo 'Run the build script and test'
- ./Build.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $BUILD_NUM > $BUILD_ARTIFACTS_FILE

deploy:
  provider: s3
  access_key_id: AKIAIY3WA4WKHQVEC7BQ
  secret_access_key: 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
  bucket: doctor-mobile-build-artifacts
  local-dir: $BUILD_ARTIFACTS_FOLDER
  acl: private

notifications:
  email:
    recipients:
    - jonas_cheng@trend.com.tw
    on_success: always
    on_failure: always
