language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-google_play_services

install:
- echo 'Install dependences'

before_script:
- echo 'Retrieve the last build status'
- export BUILD_NUM=`expr 1000+$TRAVIS_BUILD_NUMBER`
- export BUILD_ARTIFACTS_FOLDER="build"
- export BUILD_ARTIFACTS_FILE=$BUILD_ARTIFACTS_FOLDER"/"$BUILD_NUM+".txt"
- mkdir $BUILD_ARTIFACTS_FOLDER

script:
- echo 'Run the build script and test'
- ./Build.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $BUILD_NUM > $BUILD_ARTIFACTS_FILE

deploy:
  provider: s3
  access_key_id:
    secure: "AmZ4apNHQYfKn4ODA9x+iD7yoLf9uI/uyokBAw6WRzdG4AEcHq/p+zapA3H5F8z/nGzMhu5hnCnat/9AA85TGf2XmiMa/B0gKGEFvFGmqY4fk3Zzrm3r5AyAIKvNazMjS1lzV+IvvPVlZqaF/jF1PU65Q/doWnODvl8Lr3pTNvWLL39Bs3jCpxBOpwD9wprCBpIiZA7vFyf7eivw1Wkf/43CEhIhbc7NCJGLZxUpUsnvbFNu+xcePwZi2AYfUZHKm/biCHr2aX2yuuObSRVXXNVQY98PUxkOIJDgqOx1ZajhDv4Gcd32QSJtJASanYJ5KsFvQAkOB0rmMQSDD03CP7bsreu6UWd5MeApChBOVTJaHWV/rSSMvPY02YFcpzIBZwA29ybEuh2GtcoNpwcyvBYXWAfAeYmdlf/WDuNFbh74PmOBDB4fSEqGYSgD7l176QJx/2nQ00Z/qx7nx+dJ6uJ6+Vfs6EXd1Yg3EoxuEMNjE8p1cmhtcCl9E/a+Dgj1g14qP35wpKrdIShZMIj1R6gSPO5c/bSqipJ7gMvVy7HdfMUbqay5ogLE/Z8xVZG7lQBcJ7z8RFtL2VO7J391RvvmcHP5CysdrEQubQX7RSHUM/zLDQz6sIIf0vXHFZAvlxPADxhK6wtKHlF92G7QCJO+kTZW9vBY3fqz0Cp0VYw="
  secret_access_key:
    secure: "MMyz5ObEUmv3IwEPif6KD3Dvh1dg62dwRW+zq4HNYyJdI65ZmArMOBrxEvitZjEwITJH1kaaIMmMXhqNLGvADHh48tzpwhEg4TWmOU5YrSludowrOMCYzQo/WoivD46gzbGcmrxIx4e4dCH8b2imCC3xrDJzdg1SkBJKWCbDUWnixiZH1Ep0lzeGyUcHl2h62c6NgZNpZr5LAQsBm4b8kwh/Nfk4qpmsHvTFPxUtBL5pW56PI5lXeVfkUtmSBrgd9MXj/k4CJzV0Yg+u7FWZP4kyr2I6UCT17m5DgPNugBXMneKGdXQjs/DMHKqU2vWWGB6GshSpwNrnWE3BYrvwfGfoSG2tyNuB80w4tQoXj6L6uJBXrkMKvDXrLFmlJZEqmLmlviQvM2jKA2z1cXk4hMcgSxu6IWIGEwuf7AzN3CXFJOnXrHqA8Y7QRDtqzHnKygBIfadc9ivhLeBT9bogDor4W48YT3V+mwj76Unx0M1cdU/Uk+SoCxSJyPp4pB1IPp09pItkWUeyd1hvW7HAR7ZqKPdAJhHf/bR0N6s22PUFY6f6iISs5MA0Jj0oxc97Ee2Yh8kZMNkcfAja2uQeKM1udDtQPDVGSSRWhTg3HR8kRpPqJJGc5FcXbM9A5B80fjHZucsUTz03iICJ3Z2XUU/l+JC42UrMr2RKAGaAFUQ="
  bucket: doctor-mobile-build-artifacts
  local-dir: $BUILD_ARTIFACTS_FOLDER
  acl: private

notifications:
  email:
    recipients:
    - jonas_cheng@trend.com.tw
    on_success: always
    on_failure: always
